### PR TITLE
* FIX [pub_handler] fix #174

### LINKED ISSUE #174: [BUG] Data racing condition
==495130==ERROR: AddressSanitizer: heap-use-after-free on address 0x6030000985a0 at pc 0x5578a530f58a bp 0x7effaa7f57b0 sp 0x7effaa7f57a0
READ of size 8 at 0x6030000985a0 thread T10 (nng:task)
    #0 0x5578a530f589 in foreach_client ../nanomq/pub_handler.c:90
    #1 0x5578a530f91e in handle_pub ../nanomq/pub_handler.c:146
    #2 0x5578a531896f in server_cb ../nanomq/apps/broker.c:124
    #3 0x5578a53486af in nni_task_exec ../nng/src/core/taskq.c:144
    #4 0x5578a532c48b in nni_aio_finish_impl ../nng/src/core/aio.c:456
    #5 0x5578a532c50d in nni_aio_finish_sync ../nng/src/core/aio.c:473
    #6 0x5578a535a495 in nano_pipe_recv_cb ../nng/src/sp/protocol/reqrep0/nano_tcp.c:1130
    #7 0x5578a53486af in nni_task_exec ../nng/src/core/taskq.c:144
    #8 0x5578a532c48b in nni_aio_finish_impl ../nng/src/core/aio.c:456
    #9 0x5578a532c50d in nni_aio_finish_sync ../nng/src/core/aio.c:473
    #10 0x5578a536acf6 in tcptran_pipe_recv_cb ../nng/src/sp/transport/tcp/tcp.c:642
    #11 0x5578a5347eba in nni_taskq_thread ../nng/src/core/taskq.c:50
    #12 0x5578a5349124 in nni_thr_wrap ../nng/src/core/thread.c:94
    #13 0x5578a5351b4c in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:218
    #14 0x7effb2b1058f in start_thread nptl/pthread_create.c:463
    #15 0x7effb26b8222 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x119222)

0x6030000985a0 is located 16 bytes inside of 32-byte region [0x603000098590,0x6030000985b0)
freed by thread T35 (nng:reap2) here:
    #0 0x7effb2bd91c7 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:123
    #1 0x5578a534db9c in nni_free ../nng/src/platform/posix/posix_alloc.c:33
    #2 0x5578a531e84b in nng_free ../nng/src/nng.c:70
    #3 0x5578a5316e31 in del_sub_ctx ../nanomq/sub_handler.c:495
    #4 0x5578a535700f in del_topic_clictx_from_tree ../nng/src/sp/protocol/reqrep0/nano_tcp.c:449
    #5 0x5578a53587ba in nano_pipe_fini ../nng/src/sp/protocol/reqrep0/nano_tcp.c:724
    #6 0x5578a533b4f5 in pipe_destroy ../nng/src/core/pipe.c:89
    #7 0x5578a533d8ec in reap_worker ../nng/src/core/reap.c:58
    #8 0x5578a5349124 in nni_thr_wrap ../nng/src/core/thread.c:94
    #9 0x5578a5351b4c in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:218
    #10 0x7effb2b1058f in start_thread nptl/pthread_create.c:463

previously allocated by thread T20 (nng:task) here:
    #0 0x7effb2bd9527 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5578a534db42 in nni_alloc ../nng/src/platform/posix/posix_alloc.c:20
    #2 0x5578a531e804 in nng_alloc ../nng/src/nng.c:58
    #3 0x5578a531552b in sub_ctx_handle ../nanomq/sub_handler.c:286
    #4 0x5578a531933e in server_cb ../nanomq/apps/broker.c:176
    #5 0x5578a5347eba in nni_taskq_thread ../nng/src/core/taskq.c:50
    #6 0x5578a5349124 in nni_thr_wrap ../nng/src/core/thread.c:94
    #7 0x5578a5351b4c in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:218
    #8 0x7effb2b1058f in start_thread nptl/pthread_create.c:463

Thread T10 (nng:task) created by T0 here:
    #0 0x7effb2b80a65 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x5578a5351c7c in nni_plat_thr_init ../nng/src/platform/posix/posix_thread.c:231
    #2 0x5578a53493cd in nni_thr_init ../nng/src/core/thread.c:121
    #3 0x5578a53481d9 in nni_taskq_init ../nng/src/core/taskq.c:95
    #4 0x5578a5348df4 in nni_taskq_sys_init ../nng/src/core/taskq.c:284
    #5 0x5578a5332da9 in nni_init_helper ../nng/src/core/init.c:41
    #6 0x5578a5351f81 in nni_plat_init ../nng/src/platform/posix/posix_thread.c:368
    #7 0x5578a5332e60 in nni_init ../nng/src/core/init.c:61
    #8 0x5578a533d456 in nni_proto_mqtt_open ../nng/src/core/protocol.c:79
    #9 0x5578a535ab75 in nng_nano_tcp0_open ../nng/src/sp/protocol/reqrep0/nano_tcp.c:1282
    #10 0x5578a531b994 in broker ../nanomq/apps/broker.c:450
    #11 0x5578a531d6ba in broker_start ../nanomq/apps/broker.c:637
    #12 0x5578a530e83c in main ../nanomq/nanomq.c:163
    #13 0x7effb25c7cb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

Thread T35 (nng:reap2) created by T0 here:
    #0 0x7effb2b80a65 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x5578a5351c7c in nni_plat_thr_init ../nng/src/platform/posix/posix_thread.c:231
    #2 0x5578a53493cd in nni_thr_init ../nng/src/core/thread.c:121
    #3 0x5578a533db82 in nni_reap_sys_init ../nng/src/core/reap.c:115
    #4 0x5578a5332dbb in nni_init_helper ../nng/src/core/init.c:42
    #5 0x5578a5351f81 in nni_plat_init ../nng/src/platform/posix/posix_thread.c:368
    #6 0x5578a5332e60 in nni_init ../nng/src/core/init.c:61
    #7 0x5578a533d456 in nni_proto_mqtt_open ../nng/src/core/protocol.c:79
    #8 0x5578a535ab75 in nng_nano_tcp0_open ../nng/src/sp/protocol/reqrep0/nano_tcp.c:1282
    #9 0x5578a531b994 in broker ../nanomq/apps/broker.c:450
    #10 0x5578a531d6ba in broker_start ../nanomq/apps/broker.c:637
    #11 0x5578a530e83c in main ../nanomq/nanomq.c:163
    #12 0x7effb25c7cb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

Thread T20 (nng:task) created by T0 here:
    #0 0x7effb2b80a65 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x5578a5351c7c in nni_plat_thr_init ../nng/src/platform/posix/posix_thread.c:231
    #2 0x5578a53493cd in nni_thr_init ../nng/src/core/thread.c:121
    #3 0x5578a53481d9 in nni_taskq_init ../nng/src/core/taskq.c:95
    #4 0x5578a5348df4 in nni_taskq_sys_init ../nng/src/core/taskq.c:284
    #5 0x5578a5332da9 in nni_init_helper ../nng/src/core/init.c:41
    #6 0x5578a5351f81 in nni_plat_init ../nng/src/platform/posix/posix_thread.c:368
    #7 0x5578a5332e60 in nni_init ../nng/src/core/init.c:61
    #8 0x5578a533d456 in nni_proto_mqtt_open ../nng/src/core/protocol.c:79
    #9 0x5578a535ab75 in nng_nano_tcp0_open ../nng/src/sp/protocol/reqrep0/nano_tcp.c:1282
    #10 0x5578a531b994 in broker ../nanomq/apps/broker.c:450
    #11 0x5578a531d6ba in broker_start ../nanomq/apps/broker.c:637
    #12 0x5578a530e83c in main ../nanomq/nanomq.c:163
    #13 0x7effb25c7cb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

SUMMARY: AddressSanitizer: heap-use-after-free ../nanomq/pub_handler.c:90 in foreach_client
Shadow bytes around the buggy address:
  0x0c068000b060: fd fa fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c068000b070: fa fa fa fa fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c068000b080: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
  0x0c068000b090: fd fa fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c068000b0a0: fd fd fd fd fa fa fd fd fd fa fa fa fd fd fd fd
=>0x0c068000b0b0: fa fa fd fd[fd]fd fa fa fd fd fd fa fa fa fd fd
  0x0c068000b0c0: fd fa fa fa fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c068000b0d0: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fa
  0x0c068000b0e0: fa fa fd fd fd fa fa fa fa fa fa fa fa fa fa fa
  0x0c068000b0f0: fa fa fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c068000b100: fd fd fd fa fa fa fd fd fd fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==495130==ABORTING

### PR DESCRIPTION
**Pull request by JaylinYu**
temporary fix #174

### CODE REVIEW

File: nanomq/pub_handler.c [hunk 1]
```diff
@@ -84,25 +47,28 @@ foreach_client(
...
 	struct client_ctx *ctx;
 
-	for (int i = 0; i < cvector_size(cli_ctx_list); i++) {
-		equal   = false;
+	int      ctx_list_len = cvector_size(cli_ctx_list);
+	uint32_t pids[ctx_list_len];
+
+	for (int i = 0; i < ctx_list_len; i++) {
 		ctx     = (struct client_ctx *) cli_ctx_list[i];
+		pids[i] = ctx->pid.id;
```
Comment (JaylinYu) [inline nanomq/pub_handler.c:55]: still risky to use ctx pointer here. better let lib guarantee the ctx_list is threaded safe.

**Review by alvin1221 — APPROVED** [review]

**Comment by JaylinYu** [comment]
only a temporary fix, needs further action on it.
