### PR TITLE
Fixed bridge bug.

### LINKED ISSUE #431: Bridge bug.
When run bridge function, set config 
```
bridge.mqtt.forwards=topic1/topic2/#
```
subscribe to remote broker 
```
$ mosquitto_sub -t 'topic1' -h ip -p port
```
publish to 
```
mosquitto_pub -t topic1 -m "forward_msg"
```
sub client receive msg., but it should not receive msg.

### PR DESCRIPTION
**Pull request by lee-emqx**
Fixed #431

### CODE REVIEW

File: nanomq/bridge.c [hunk 1]
```diff
@@ -130,38 +130,129 @@ bridge_client(nng_socket *sock, conf_bridge *config)
...
+	while (*topic_queue) {
+		t = *topic_queue;
+		topic_queue++;
+		zfree(t);
+		t = NULL;
+	}
 
-	char *origin_str = strdup(origin);
-	char *input_str  = strdup(input);
+	if (tq) {
```
Comment (alvin1221) [inline nanomq/bridge.c:203]: Nothing here ?

**Review by alvin1221 — APPROVED** [review]

**Review by JaylinYu — APPROVED** [review]
